### ISSUE TITLE
Electronic Data Sheet

### ISSUE THREAD

**Issue by alberthli** [ros-industrial/ros2_canopen#174]
I am hoping to use `ros2_canopen` to communicate with an [Allegro hand](http://wiki.wonikrobotics.com/AllegroHandWiki/index.php/Allegro_Hand_v4.0). However, it doesn't seem like there is an EDS available for it. I was wondering
1. Is there an easy way to generate EDS files?
2. Is there a workaround for using `ros2_canopen` without an EDS file?

**Comment by ipa-cmh** [comment]
Hi, allegro hand does not use CANopen but a custom protocol based on CAN bus. You'll have to implement it yourself. I recommend looking at https://github.com/autowarefoundation/ros2_socketcan

**Comment by alberthli** [comment]
Thank you for the clarity. I'll give it a shot.
