### ISSUE TITLE
Ros2_Canopen w/ Nanotec Controller

### ISSUE THREAD

**Issue by r9-pena** [ros-industrial/ros2_canopen#175]
**Describe the bug**
I am trying to attach a nanotec controller (CL3-E-2-0F) to operate a BLDC motor (DB42M03). I created a single-motor package configuration using the Canopen tutorial and the Trinamic Stepper Motor example. However, I get the errors shown in the attached images. I would greatly appreciate any help in resolving this issue and getting the motor to operate w/ ROS2.

**Logs**
Add build or execution log for context.

**Setup:**
 - Device: Jetson AGX Orin
 - OS: Linux
 - ROS-Distro: Foxy
 - Branch/Commit: Foxy

**Additional context**
I have also attached a link to the package repository, for any clarification on the code.
[https://github.com/r9-pena/drive_motor.git](https://github.com/r9-pena/drive_motor.git)

![image](https://github.com/ros-industrial/ros2_canopen/assets/55148641/87e23bdb-f454-4eb4-85ad-744450ef8220)

**Comment by ipa-cmh** [comment]
Looks like you do find_package(ros2_canopen) in CmakeLists.txt. ros2_canopen is not a package but a repository containing packages. You probably want find_package(canopen). Also we do not support foxy and the branch is super outdated...

**Comment by ipa-vsp** [comment]
#176

**Comment by ipa-vsp** [comment]
#176 Fixed the package creation command in the documentation.

**Comment by ipa-cmh** [comment]
This seems to be stale. If you need more support, please feel free to reopen.
