### ISSUE TITLE
Problem building lely_core_libraries 

### ISSUE THREAD

**Issue by jonaskonig** [ros-industrial/ros2_canopen#177]
**Describe the bug**
When building via `colcon build` the following output is generated: 
```
Starting >>> lely_core_libraries
Starting >>> canopen_interfaces
Starting >>> roboter_sensor_controller
Starting >>> rplidar_ros
--- stderr: lely_core_libraries                                                                                                                                                
fatal: not a git repository (or any of the parent directories): .git
gmake[2]: *** [CMakeFiles/upstr_lely_core_libraries.dir/build.make:125: upstr_lely_core_libraries-prefix/src/upstr_lely_core_libraries-stamp/upstr_lely_core_libraries-update] Error 128
gmake[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/upstr_lely_core_libraries.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< lely_core_libraries [0.32s, exited with code 2]
```
I don't understand what that means and how to fix it.

**Setup:**
 - Device: intel Nuc
 - OS: Ubunut 22.04
 - ROS-Distro: Humble
 - Branch/Commit: Humble

**Comment by jonaskonig** [comment]
No, there is a working internet connection. It can't find the reference where to pull from. I re-cloned the repo, but this did not change the behavior.

**Comment by jonaskonig** [comment]
I am trying to figure out how and why. But after completely uninstalling ros2 and reinstalling it, it now works again.

**Comment by ipa-cmh** [comment]
Interesting. But great that it now works!

**Comment by jclinton830** [comment]
I have the same exact problem. Is there any other way to fix this without having to reinstall ROS2?
