### ISSUE TITLE
ros2_canopen - colcon build

### ISSUE THREAD

**Issue by zhiyiopp** [ros-industrial/ros2_canopen#190]
**Describe the bug**
after download the package, following the operation steps, in "colcon build" then:
Starting >>> lely_core_libraries
--- stderr: lely_core_libraries                                                                           
CMake Error at /opt/ros/foxy/share/ament_cmake_python/cmake/ament_python_install_package.cmake:34 (message):
  ament_python_install_package() called with unused arguments:
  SCRIPTS_DESTINATION;lib/cogen
Call Stack (most recent call first):
  /opt/ros/foxy/share/ament_cmake_python/cmake/ament_python_install_package.cmake:28 (_ament_cmake_python_install_package)
  CMakeLists.txt:41 (ament_python_install_package)
---
Failed   <<< lely_core_libraries [0.30s, exited with code 1]
Aborted  <<< canopen_interfaces [9.23s]                         

**Logs**
Add build or execution log for context.

**Setup:**
 - Device: VM 
 - OS: Ubuntu 20.04.6 LTS
 - ROS-Distro: ros2-foxy
 - Branch/Commit:

**Additional context**

**Comment by ipa-cmh** [comment]
We don't support foxy anymore. It is end of life. Please use humble (humble branch) or iron or rolling.

**Comment by zhiyiopp** [comment]
oh, i will upgrade it and try again.

**Comment by sam-tj** [comment]
I had the same problem with humble, used humble branch to make it work.

**Comment by ipa-cmh** [comment]
@sam-tj can you post the exact error?

**Comment by sam-tj** [comment]
This is the error.

![image](https://github.com/ros-industrial/ros2_canopen/assets/20317637/c7aded39-c095-4acd-aa4a-574bf379ea4f)

**Comment by ipa-cmh** [comment]
This is because QoS initialization as it was done in humble is deprecated in Iron and Rolling and the new way does not work in humble. You currently use master branch of this repo but you have to use the Humble branch to work with humble.

**Comment by sam-tj** [comment]
Yes, that's why I moved to humble branch and that works for me.
