### ISSUE TITLE
Change SDO timeout setting?

### ISSUE THREAD

**Issue by gsalinas** [ros-industrial/ros2_canopen#194]
Hi again!

I've run into an issue doing PDO configuration at the startup of my node where the SDO responses from my device to the configuration messages being received occasionally time out. This could of course be for a variety of reasons and may require further debugging, but in some cases my Wireshark traces show that the device does send a response, sometimes only ~10ms too late, at which point the SDO download has already failed, and the PDO configuration fails as well. Is there a way to configure the SDO timeout settings of my master or my devices?

Thank you so much for your help!

**Comment by ipa-cmh** [comment]
There is a setting in the underlying lelycore library for this, we just currently do not expose it. I'll have to check on the work necessary to expose.

**Comment by gsalinas** [comment]
Thank you for looking into it!

**Comment by ipa-cmh** [comment]
@ipa-vsp will create a pr for this in the coming days. It will expose this timeout as setting to be set in bus.yml in the master section.

**Comment by ipa-vsp** [comment]
#220
