### ISSUE TITLE
Can Fake Slaves Used in Examples be Operated in Velocity Mode? 

### ISSUE THREAD

**Issue by Fionn-OMuiri** [ros-industrial/ros2_canopen#195]
**Question**
Hi there. I'm just wondering if the fake slave nodes used in the ROS2 CANOpen examples can be operated in velocity mode, or if they are just setup to run in position mode at the minute?

Thanks

**Comment by ipa-cmh** [comment]
Currently, only profiled, cyclic and interpolated position mode are supported. Adding Velocity mode would not be a big issue if you are okay with simple mirroring of values. If you need more such as modeling Acceleration or profile, then it is more work.

**Comment by Fionn-OMuiri** [comment]
Okay that's perfect, thanks very much
