### ISSUE TITLE
Humble QoS issues in ROS2_canopen

### ISSUE THREAD

**Issue by sandropp** [ros-industrial/ros2_canopen#217]
**Describe the bug**
This is because QoS initialization as it was done in humble is deprecated in Iron and Rolling and the new way does not work in humble. You currently use master branch of this repo but you have to use the Humble branch to work with humble.
the question is: how to use the humble branch to make it work? which command have to use?

**Logs**
Add build or execution log for context.

**Setup:**
 - Device: VM
 - OS: ubuntu 22.04 
 - ROS-Distro: humble
 - Branch/Commit:

**Additional context**

**Comment by ipa-vsp** [comment]
Hi @sandropp,

Please find below the tutorial on how to switch the git remote branch:
1. https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch
2. https://www.freecodecamp.org/news/git-checkout-remote-branch-tutorial/

After successfully checking out the humble branch, you should be able to build the package without any issues.
