### ISSUE TITLE
COData only allows UINT

### ISSUE THREAD

**Issue by VerlooyNick** [ros-industrial/ros2_canopen#218]
I'm using the proxy driver to operate a Nanotec PD4-C BLDC motor. 
The motor's PDO velocity target accepts signed integers to allow for negative speeds. 

The [COdata](https://github.com/ros-industrial/ros2_canopen/blob/master/canopen_interfaces/msg/COData.msg) only accepts unsigned integers as data. 
Is there a specific reason for this?

**Comment by ipa-cmh** [comment]
Hi,

The CANopen Stack is aware of the dataype the target sdo has. The data is exactly only data. It will be interpreted as an int32, int16, int8 or uint8, uint16, unit32 depending on the entry in the dcf/eds file.
