### ISSUE TITLE
  1 package failed: lely_core_libraries

### ISSUE THREAD

**Issue by leeyunhome** [ros-industrial/ros2_canopen#27]
**Describe the bug**

Failed to build
-###########################################################################
error: invalid command 'bdist_wheel'
make[6]: *** [python-bdist_wheel] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [upstr_lely_core_libraries-prefix/src/upstr_lely_core_libraries-stamp/upstr_lely_core_libraries-build] Error 2
make[1]: *** [CMakeFiles/upstr_lely_core_libraries.dir/all] Error 2
make: *** [all] Error 2
     
Failed   <<< lely_core_libraries [4min 21s, exited with code 2]
Aborted  <<< topic_service_action_rclcpp_example [2min 42s]

Summary: 14 packages finished [4min 35s]
  1 package failed: lely_core_libraries
  1 package aborted: topic_service_action_rclcpp_example
  8 packages had stderr output: canopen_utils lely_core_libraries logging_rclpy_example my_first_ros_rclpy_pkg ros2env tf2_rclpy_example time_rclpy_example topic_service_action_rclpy_example
  5 packages not processed
###########################################################################

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

Success to build

**Logs**

**Setup:**
 - Device: Nvidia jetson nano
 - OS: Jetson OS(arm64 ubuntu 18.04)
 - Distro: [e.g. stock browser, safari]
 - Branch/Commit:

**Additional context**

Can you tell me how to resolve this build error?

Thank you.

**Comment by ipa-cmh** [comment]
Seems you are building on arm architecture. We have not tested this yet.
Which ROS distro are you using?
Can you post the build log? That should give a bit more information about the error.

Potentially, you need to install wheel on your system.
pip3 install wheel

**Comment by leeyunhome** [comment]
> 

Hello, @ipa-cmh 
Thank you for reply.

Which ROS distro are you using? 
=>I'm using a ROS2 foxy docker image in ubuntu18.04  on jetson nano devkit.

Can you post the build log? That should give a bit more information about the error.
=> I'll post it sooner or later

Potentially, you need to install wheel on your system.
pip3 install wheel
=> I'll try it.

Thank you.

**Comment by leeyunhome** [comment]
> Seems you are building on arm architecture. We have not tested this yet. Which ROS distro are you using? Can you post the build log? That should give a bit more information about the error.
> 
> Potentially, you need to install wheel on your system. `pip3 install wheel`

Hello,

Here's log.
`manager@manager-desktop:~/robot_ws$ colcon build --symlink-install
Starting >>> canopen_interfaces
Starting >>> lely_core_libraries
Starting >>> msg_srv_action_interface_example
Starting >>> canopen_utils                                                                     
Finished <<< msg_srv_action_interface_example [8.10s]                                                      
Starting >>> logging_rclpy_example
Finished <<< canopen_utils [9.95s]                                                                                
Starting >>> my_first_ros_rclcpp_pkg
Finished <<< logging_rclpy_example [6.47s]                                                                           
Starting >>> rqt_example
Finished <<< my_first_ros_rclcpp_pkg [6.17s]                                                                         
Starting >>> time_rclcpp_example
Finished <<< rqt_example [6.30s]                                                                                     
Starting >>> time_rclpy_example                                                                                      
Finished <<< time_rclcpp_example [10.9s]                                                                              
Starting >>> topic_service_action_rclcpp_example
Finished <<< time_rclpy_example [11.9s]                                                                               
[Processing: canopen_interfaces, lely_core_libraries, topic_service_action_rclcpp_example]                                
Finished <<< topic_service_action_rclcpp_example [47.3s]                                
[Processing: canopen_interfaces, lely_core_libraries]                                   
Finished <<< canopen_interfaces [1min 59s]                                                                                     
[Processing: lely_core_libraries]                                          
[Processing: lely_core_libraries]                                          
[Processing: lely_core_libraries]                                          
[Processing: lely_core_libraries]                                          
--- stderr: lely_core_libraries                                             
Cloning into 'upstr_lely_core_libraries'...
Note: checking out 'f13629b4fcc042744ff497c8bf7428cf2775aba8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f13629b4 CI: use GCC 11 by default
configure.ac:17: installing './compile'
configure.ac:6: installing './config.guess'
configure.ac:6: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
configure.ac:606: installing './tap-driver.sh'
src/can/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
libtool: warning: relinking 'liblely-tap.la'
libtool: warning: relinking 'liblely-util.la'
libtool: warning: relinking 'liblely-can.la'
libtool: warning: relinking 'liblely-co.la'
libtool: warning: relinking 'liblely-io.la'
libtool: warning: relinking 'liblely-ev.la'
libtool: warning: relinking 'liblely-io2.la'
libtool: warning: relinking 'liblely-coapp.la'
libtool: warning: relinking 'liblely-tap.la'
libtool: warning: relinking 'liblely-util.la'
libtool: warning: relinking 'liblely-can.la'
libtool: warning: relinking 'liblely-co.la'
libtool: warning: relinking 'liblely-io.la'
libtool: warning: relinking 'liblely-ev.la'
libtool: warning: relinking 'liblely-io2.la'
libtool: warning: relinking 'liblely-coapp.la'
---
Finished <<< lely_core_libraries [4min 15s]
Starting >>> canopen_core    
--- stderr: canopen_core                                 
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "Findyaml_cpp_vendor.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "yaml_cpp_vendor", but CMake did not find one.

  Could not find a package configuration file provided by "yaml_cpp_vendor"
  with any of the following names:

    yaml_cpp_vendorConfig.cmake
    yaml_cpp_vendor-config.cmake

  Add the installation prefix of "yaml_cpp_vendor" to CMAKE_PREFIX_PATH or
  set "yaml_cpp_vendor_DIR" to a directory containing one of the above files.
  If "yaml_cpp_vendor" provides a separate development package or SDK, be
  sure it has been installed.


---
Failed   <<< canopen_core [7.74s, exited with code 1]

Summary: 10 packages finished [4min 24s]
  1 package failed: canopen_core
  2 packages had stderr output: canopen_core lely_core_libraries
  4 packages not processed`

Thank you.

**Comment by ipa-cmh** [comment]
Did you run:

```bash
rosdep install --from-paths src/ros_canopen --ignore-src
```

It seems you are missing a bunch of dependencies for the build.

**Comment by ipa-cmh** [comment]
This seems to be stale.
