### ISSUE TITLE
Can use CANOpen on EtherCAT network ?.

### ISSUE THREAD

**Issue by dpflexvn** [ros-industrial/ros2_canopen#276]
Hello,
I have simple EtherCAT demo set:
- Master: a PC installed Ubuntu 22.04, ROS2 Humble, Moveit, IgH EtherCAT Master
- Slave: a servo drive support EtherCAT, support CiA402.

Can I use ros2_canopen package to communicate between Master & Slave ?.
Is it possible ?. If not, any advise to do it ?.
Thank you.

**Comment by ipa-vsp** [comment]
Take a look at this: [https://github.com/ICube-Robotics/ethercat_driver_ros2](https://github.com/ICube-Robotics/ethercat_driver_ros2)

**Comment by hellantos** [comment]
Currently, you cannot use this stack for ethercat. The way to go would be as @ipa-vsp suggested.

**Comment by dpflexvn** [comment]
Tks hellantos.
