### ISSUE TITLE
cyclic_torque_mode missing in Cia402 Driver?

### ISSUE THREAD

**Issue by chinaheyu** [ros-industrial/ros2_canopen#292]
I noticed that only `cyclic_position_mode` and `cyclic_velocity_mode` are provided by Cia402 Driver, but `cyclic_torque_mode` seems to be missing.

<img width="564" alt="image" src="https://github.com/ros-industrial/ros2_canopen/assets/59406481/dc2b20a4-c9c9-4bc9-99b5-68f854da43ba">

I found some relevant  code, but `Cyclic_Synchronous_Torque` is not used at all.

https://github.com/ros-industrial/ros2_canopen/blob/e6db3cf2129fd03abbcb56c6a063b92184949a06/canopen_402_driver/include/canopen_402_driver/base.hpp#L49

Controlling the torque is important to us. It would be appreciated if anyone tell us how to address this.

**Comment by hellantos** [comment]
See PR #293
