### ISSUE TITLE
WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'ros_canopen' in --packages-select

### ISSUE THREAD

**Issue by leeyunhome** [ros-industrial/ros2_canopen#31]
Hello, @ipa-nhg @mathias-luedtke @JeremyZoss @gavanderhoorn @Briancbn 

**Describe the bug**
root@manager-desktop:~/ros2_canopen_ws# colcon build --packages-select ros_canopen
[2.291s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'ros_canopen' in --packages-select
                     
Summary: 0 packages finished [0.90s]

**Logs**
Add build or execution log for context.

**Setup:**
 - Device: Nvidia jetson nano(jetpack 4.6)
 - OS: arm64 ubuntu18.04
 - ROS-Distro: foxy-ros-base-l4t-r32.6.1 docker image
 - Branch/Commit:

**Additional context**

**Comment by ipa-cmh** [comment]
I suppose this is solved, so I will close this issue.
