### ISSUE TITLE
Add test for proxy driver rpdo/tpdo behaviour

### ISSUE THREAD

**Issue by ipa-cmh** [ros-industrial/ros2_canopen#81]
**Is your feature request related to a problem? Please describe.**
There is a bug report #46 about the rpdo/tpdo topic behaviour.

**Describe the solution you'd like**
There should be a launch test in canopen_tests to test the behaviour, similarly to what is done in the sdo tests.

**Comment by ipa-cmh** [comment]
#97 adds this.

**Comment by ipa-vsp** [comment]
#98

**Comment by ipa-vsp** [comment]
#98
